name: cd/ci pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk:
    name: snyk scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: nodejs setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install snyk
        run: npm install -g snyk

      - name: auth snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: run snyk test (backend)
        working-directory: backend
        run: snyk test || true

      - name: run snyk test (frontend)
        working-directory: frontend
        run: snyk test || true

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: npm install

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: npm install
