name: cd/ci pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: nodejs setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install snyk
        run: npm install -g snyk

      - name: auth snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: run snyk test (backend) and generate report
        working-directory: backend
        run: snyk test --severity-threshold=high --json > snyk-backend-report.json || true

      - name: upload backend report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-backend-report
          path: backend/snyk-backend-report.json

      - name: run snyk test (frontend) and generate report
        working-directory: frontend
        run: snyk test --severity-threshold=high --json > snyk-frontend-report.json || true

      - name: upload frontend report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-frontend-report
          path: frontend/snyk-frontend-report.json

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install

  zap_scan:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Run ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://8dd6-178-90-44-225.ngrok-free.app/'
          fail_action: false
          allow_issue_writing: false

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: owasp-zap-report.html
