name: cd/ci pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk:
    name: Snyk Scan (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test (Python project in frontend/)
        working-directory: frontend
        run: snyk test

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-frontend-report
          path: frontend/snyk-frontend-report.json

  build-frontend:
    name: Dummy Build (for dependency)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print placeholder
        run: echo "No actual frontend build. Added for pipeline structure."

  zap-scan:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Run ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://8dd6-178-90-44-225.ngrok-free.app/'
          fail_action: false
          allow_issue_writing: false
          cmd_options: >
            -r zap-report.html
            -J zap-report.json
            -w zap-report.md

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap-report.html
            zap-report.json
            zap-report.md
