name: cd/ci pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: nodejs setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install snyk
        run: npm install -g snyk

      - name: auth snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: run snyk test (backend) and generate report
        working-directory: backend
        run: snyk test --severity-threshold=high --json > snyk-backend-report.json || true

      - name: upload backend report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-backend-report
          path: backend/snyk-backend-report.json

      - name: run snyk test (frontend) and generate report
        working-directory: frontend
        run: snyk test --severity-threshold=high --json > snyk-frontend-report.json || true

      - name: upload frontend report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-frontend-report
          path: frontend/snyk-frontend-report.json

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install

name: OWASP ZAP Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zap-scan:
    name: Run OWASP ZAP Scan
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настройка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Шаг 3: Установка зависимостей (если требуется)
      - name: Install dependencies (backend)
        run: npm install
        working-directory: backend

      - name: Install dependencies (frontend)
        run: npm install
        working-directory: frontend

      # Шаг 4: Запуск серверов
      - name: Start Backend
        run: npm start &
        working-directory: backend

      - name: Start Frontend
        run: npm start &
        working-directory: frontend

      # Шаг 5: Ожидание старта серверов
      - name: Wait for servers to start
        run: sleep 25

      # Шаг 6: Запуск OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'  # Укажите URL вашего приложения
          fail_action: false  # Не завершать процесс при нахождении уязвимостей
          allow_issue_writing: false  # Не записывать найденные уязвимости
          config_file: .zap/config.yaml  # Укажите путь к вашему конфигурационному файлу, если он есть

      # Шаг 7: Загрузка отчета ZAP
      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: owasp-zap-report.html  # Укажите путь к вашему отчету

      # Шаг 8: Остановка серверов
      - name: Kill background processes
        if: always()
        run: |
          pkill -f "npm start" || true
